language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules

before_install:
  - openssl aes-256-cbc -K $encrypted_236e6c9c4fa5_key -iv $encrypted_236e6c9c4fa5_iv -in secrets.yml.enc -out secrets.yml -d

install:
  - lerna bootstrap

script:
  - lerna run --parallel build

deploy:
  - serverless deploy
