language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_236e6c9c4fa5_key -iv $encrypted_236e6c9c4fa5_iv -in secrets/secrets.yml.enc -out secrets/secrets.yml -d
install:
  - npm install -g serverless
  - npm install
  - npm run bootstrap
script:
  - lerna run --parallel build
deploy:
  provider: script
  script: serverless deploy
  on:
    branch: feat-typescript
