service: when-notification-app

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}

plugins:
  - serverless-offline

package:
  include:
    - node_modules/**
    - src/**
  exclude:
    - /**

functions:
  graphql:
    handler: src/handler.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
