service: when-notification-app

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  region: eu-central-1
  environment:
    IS_OFFLINE: true
    HVV_API_VERSION: 36
    TIMETABLE_TABLE: 'when-timetable'
    USER_TABLE: 'when-user-table'
    CONNECTION_TABLE: 'when-connection-table'
    CENTURIA_TABLE: 'when-centuria-table'

package:
  include:
    - node_modules/**
    - build/**
  exclude:
    - /**

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: /src/offline/migrations

functions:
  updateTimetable:
    handler: '/build/functions/update-timetable.updateTimetable'
    events:
      - schedule: cron(0 4 * * ? *)
  checkTimetable:
    handler: '/build/functions/check-timetable.checkTimetable'
  hvvRouteRequest:
    handler: '/build/functions/hvv-route-request.routeRequest'
  createUser:
    handler: '/build/functions/create-user.createUser'
    events:
      - http:
          path: users/create
          method: get
          request:
            parameters:
              querystrings:
                phone: true

resources:
  Resources:
    TimeDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: centuria
            AttributeType: S
        KeySchema:
          - AttributeName: centuria
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.TIMETABLE_TABLE}
    UserDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.USER_TABLE}
    ConnectionDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.CONNECTION_TABLE}
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    CenturiaDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.CENTURIA_TABLE}
        
