service: when-notification-app

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  region: eu-central-1
  environment:
    IS_OFFLINE: true
    HVV_API_VERSION: 36
    TIMETABLE_TABLE: 'when-timetable'
    USERS_TABLE: 'when-users'

package:
  include:
    - node_modules/**
    - build/**
  exclude:
    - /**

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: /src/offline/migrations

functions:
  updateTimetable:
    handler: '/build/functions/update-timetable.updateTimetable'
    events:
      - schedule: cron(0 4 * * ? *)
  hvvRequest:
    handler: '/build/functions/hvv-request.hvvRequest'

resources:
  Resources:
    TimeDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: centuria
            AttributeType: S
        KeySchema:
          - AttributeName: centuria
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.TIMETABLE_TABLE}
    UsersDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
        DeletionPolicy: Retain
        Properties:
          AttributeDefinitions:
            - AttributeName: phone
              AttributeType: S
          KeySchema:
            - AttributeName: phone
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
          TableName: ${self:provider.environment.USERS_TABLE}


