service: when-notification-app

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  region: eu-central-1
  environment:
    IS_OFFLINE: true
    TIMETABLE_TABLE: 'when-timetable'

package:
  include:
    - node_modules/**
    - build/**
  exclude:
    - /**

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: /src/offline/migrations

functions:
  updateTimetable:
    handler: '/build/functions/update-timetable.updateTimetable'
    events:
      - schedule: cron(0 4 * * ? *)

resources:
  Resources:
    TimeDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.TIMETABLE_TABLE}
